name: Test package

on: [push]

jobs:
  build:
    name: ${{ matrix.config.env }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        config:
          - python: 3.6
            env: py36
          - python: 3.7
            env: py37
          - python: 3.8
            env: py38
          - python: 3.7
            env: lint
          - python: 3.6
            env: docs
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.config.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.config.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-pip-version
    - name: Lint with tox
      run: |
        TOXENV=${{ matrix.config.env }} tox
