name: Test package

on: [push]

jobs:
  build:
    name: ${{ matrix.config.env }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        config:
          - python: 3.7
            env: py37
          - python: 3.8
            env: py38
          - python: 3.9
            env: py39
          - python: 3.9
            env: lint
          - python: 3.9
            env: docs
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.config.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.config.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-pip-version
    - name: Lint with tox
      run: |
        TOXENV=${{ matrix.config.env }} tox
  build-n-publish:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build a binary wheel and a source tarball
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel
    - name: Publish distribution 📦to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        password: ${{ secrets.PYPI_PASSWORD }}
